### ISSUE TITLE
Fix case-sensitive filenames

### ISSUE THREAD

**Issue by krt16s** [tranquvis/SimpleSmsRemote#1]
Java is case-sensitive and requires public classes to be stored in a file accordingly, so app/src/main/java/tranquvis/simplesmsremote/Utils/Regex/PatternP`A`ram.java should actually be named app/src/main/java/tranquvis/simplesmsremote/Utils/Regex/PatternP`a`ram.java.

**Comment by tranquvis** [comment]
Thank you, 
issue has been fixed.
