### ISSUE TITLE
Automatic running ability?

### ISSUE THREAD

**Issue by AlfaOmega33** [tranquvis/SimpleSmsRemote#10]
Ok, this is particular but I think it will be useful: 

It would be interesting, once the cell phone is lost or stolen, can install the app remotely (through the play store) and "retrieve" the phone .. so it would be Is it possible to configure the app so that it will automatically activate once installed by the Play Store?

**Comment by tranquvis** [comment]
Seems that this is not possible.
The problem is described here: https://stackoverflow.com/a/8535062/3198937.
