### ISSUE TITLE
location as URL to map

### ISSUE THREAD

**Issue by AlbertoDiazC** [tranquvis/SimpleSmsRemote#15]
First of all, thank you for your efforts.

This is my request: SimpleSMSRemote sends location as latitude-longitude numbers, which isn't very user friendly. If possible, please add an option to enable sending location as a clickable URL. For example: https://www.google.com/maps?q=48.197611,15.780512

**Comment by pl31** [comment]
Thanks from my side as well. Great App with nice UI.
Clickable url would be really nice. Are there any GPS quality informations, which could be added to the message as well?

**Comment by tranquvis** [comment]
The API also provides an accuracy property. I will add that in the next version.

**Comment by tranquvis** [comment]
I implemented your feature requests in this commit: https://github.com/tranquvis/SimpleSmsRemote/commit/d35d29547324ab74d23e5d78e8b8c566f818e9fd 🏆 
Thank you for your contributions.

**Comment by pl31** [comment]
Awesome! Thanks.

**Comment by pl31** [comment]
Hello Tranquis, 

I tried the new version and it works great. 

The quality informations are good as well, but there is still one edge case where those are not sufficent/misleading: the location api may give an old position. I got a position with "17m accuracy (68% probability)" but I was more than 100km away.

I took a look in the api and found a property getTime to get the date/time of the fix. Could you add the date when the location was updated to the sms as well?

Shall I create a new issue, or is it fine here?

Regards
Patrick

**Comment by tranquvis** [comment]
Thank you for the information Patrick,
Would be great, if you could create an issue.
