### ISSUE TITLE
"friends" numbers

### ISSUE THREAD

**Issue by ghost** [tranquvis/SimpleSmsRemote#18]
Hi. Please add, in the settings, the ability to to define the "friends" numbers list who can send the commands

**Comment by tranquvis** [comment]
Do you mean, that a phone in this list should be able to send every command?

**Comment by protoloo** [comment]
Exactly. Also to prevent a wrong command from coming in or to prevent anyone with the app from attempting and gaining control over the phone. In short, only authorized numbers must have this possibility, for privacy and security.

**Comment by tranquvis** [comment]
If I understand it correctly, we already have this feature, but on module level.
