### ISSUE TITLE
integration with other apps

### ISSUE THREAD

**Issue by protoloo** [tranquvis/SimpleSmsRemote#19]
I do not know if it is possible, but I would like to ask you to add integration with these apps in order to extend the functionality of SimpleSmsRemote without having to add code to do things that do other apps, in particular, record audio, calls and videos with these: "Audio Recorder" (https://f-droid.org/packages/com.github.axet.audiorecorder/), "Call Recorder" (https://f-droid.org/packages/com.github.axet.callrecorder/) and "Open Camera" (https://f-droid.org/packages/net.sourceforge.opencamera/). And maybe even the option to send the audio as soon as there is wi-fi.

**Comment by tranquvis** [comment]
Connecting to other apps would be absolutely great!
The problem is that the other app needs to provide an interface.
For example, "Audio Recorder" needs to provide an interface for starting and stopping.

Implementing the functionality of other apps in SimpleSmsRemote would be possible, but is still a great effort.

**Comment by protoloo** [comment]
I get it. In the coming days I will try to contact the developers of these apps and see if they are available to implement these features or collaborate in other ways.

**Comment by protoloo** [comment]
Unfortunately did not go well .. (https://gitlab.com/axet/android-audio-recorder/issues/52#note_54764344), that's all:

For you infromation, here are two command which helps you to start recording (with visible activity) and stop recording. No sending files or hidden features added!
# adb shell am start -n com.github.axet.audiorecorder/.activities.RecordingActivity
# adb shell am broadcast -a com.github.axet.audiorecorder.STOP_RECORDING

The developer of Open Camera, however, has not yet answered me

**Comment by tranquvis** [comment]
Thank you protoloo!

Implementing a recording module by using this app wont be a great effort.
I hope this commands also work in standby.
I will try soon.

Would be interesting to know for which purpose people are using my app...

**Comment by tranquvis** [comment]
I added the module "Audio Recording" with the latest commit.
The module uses com.github.axet.audiorecorder and provides commands for starting and stopping recording.
The commands executed successfully on my phone.
