### ISSUE TITLE
Icon ic_mic_grey_700_36dp not found

### ISSUE THREAD

**Issue by pl31** [tranquvis/SimpleSmsRemote#22]
I cloned the repository and tried to build using AndroidStudio. Everything worked immediately, except line 21 in "ModuleAudioRecording":'
`this.iconRes = R.drawable.ic_mic_grey_700_36dp;`

The mic icon could not be found. (For testing I replaced with another icon).

Did I miss anything during build?

Cheers
Patrick

**Comment by tranquvis** [comment]
Forgot to add the files to git...
Fixed in e5ea23592a85c2c77ac1b3d67cb731622e66069b.
