### ISSUE TITLE
Icon / logo proposal for the application

### ISSUE THREAD

**Issue by s-yous** [tranquvis/SimpleSmsRemote#25]
Hello @tranquvis ,
I'm willing to design a new icon and a logo for your application , and i need your permission before start.

**Comment by tranquvis** [comment]
Hello @s-yous ,
sure! Thanks for your help. 
I'm curious about your design. 😄

**Comment by s-yous** [comment]
![intro](https://user-images.githubusercontent.com/37163527/38141352-96834530-342f-11e8-90ea-dd9288641aed.png)

Hello @tranquvis ,

Firstly I'm sorry for being late , so let's start by the logo / icon idea and where i got this shape : 

![idea](https://user-images.githubusercontent.com/37163527/38141378-bf4c9a0c-342f-11e8-8d72-e45c3a229d7b.png)

So i tried to combine the SMS bubble with the signal which represents the remoting control .

Now , let's compare the original and the proposal logo :D 

![old-new](https://user-images.githubusercontent.com/37163527/38141434-0d03619a-3430-11e8-9880-6107cfca4f6a.png)

I intentionally used the primary color and the primary dark of the application to let the users to be familiar with the original logo and the main colors of the application .

That's how it'll looks like on the Google Play : 

![old-new-playstore](https://user-images.githubusercontent.com/37163527/38141431-0872f2bc-3430-11e8-80c3-2a4a3031548c.png)

That's how the icon looks like in different sizes : 

![size variation](https://user-images.githubusercontent.com/37163527/38141427-03fc4742-3430-11e8-9ce0-a865727870c3.png)

This is the logotype : 

![logotype](https://user-images.githubusercontent.com/37163527/38141423-ff8fc814-342f-11e8-9b26-81eadfbdbf79.png)

I hope you'll like my design , let me know if you need any changes of some other color variation.

**Comment by tranquvis** [comment]
Hello @s-yous ,

I have to say that I am impressed of your work.
I didn't expect such a professional preparation.

The new logo is great! 
It's simple, modern, it stands out from other apps, the primary color is more present than before and the statement should fit. 👍 
The app's primary color is quite bold but I like it. 😅 
I would not make any changes.

Thanks for your great work. 
You have a new fan. 😉

**Comment by s-yous** [comment]
Thank you @tranquvis , I'm really glad that you like my design that much 😍 

I'll generate the necessary files with the monochrome version ( black and white ) with the editable files as well .

**Comment by s-yous** [comment]
I made some other color variation if you want to see the icon in different colors 
 
![color variation](https://user-images.githubusercontent.com/37163527/38156219-4714ad28-3474-11e8-9362-d7b33be58f85.png)

This is the monochrome version of the logotype and the icon 

![monochrome version](https://user-images.githubusercontent.com/37163527/38156213-413ce640-3474-11e8-890a-16d5f15b2a88.png)

I uploaded all editable files ( AI - PDF - EPS - SVG ) and the bitmap version ( PNG ) of the logotype and the icons and also the folder named ic_launcher.zip which contains the icon in different densities ( hpdi , xhdpi .. ) to use them directly as your icon launcher for the application , [Download Here](https://drive.google.com/open?id=1IhafNX1YG3HepXaxCS9z_iR30D0_3k5z) .

I wish you like my design and use it as your official icon / logo in the near future 😍 
Thank you for this opportunity :D

**Comment by tranquvis** [comment]
Thank you!

I will stay with Purple.
My plan is to publish the update next week

**Comment by tranquvis** [comment]
Hello @s-yous ,

I'm currently importing your logo.

Android now provides a way to seperate launcher icons into foreground and background called **adaptive icons**.
This is very useful because some launchers, don't support custom shapes and use round containers.
This is the result, if I use your icon:
![image](https://user-images.githubusercontent.com/8074528/38767287-a3d4d0ea-3fde-11e8-87f9-64295efe5234.png)

In order to fill the whole space, we should use the white content as foreground and set the color as background.
I already did this, but I wanted to inform you for the future.

For more information see: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by tranquvis** [comment]
How did you create the zip with the android res files?
I wrote a script, which renames the illustrator exports and creates folders for them.
I would like to know if there is an easier way.

**Comment by s-yous** [comment]
Hello @tranquvis ,
Thank you for the great information , this feature is added only for the API 26 , or it works of earlier versions ?

I used [Android Asset Studio](https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html) for generate the icon in different sizes .

I'll update the drive folder to add the shape separately , so you can use the above link .

**Comment by tranquvis** [comment]
Yes, the adaptive icon is marked with version 26. We need to provide a non-adaptive icon for older versions too.

**Comment by tranquvis** [comment]
Generating the adaptive icon in Android Studio is very simple. You only need to provide a svg for the foreground and the background color if necessary. It generates the adaptive icon as well as the normal icon for me. I can set the shape like in Android Asset Studio.

**Comment by s-yous** [comment]
I updated the Drive folder , ' Foreground.svg ' ( it's white and the background is white also , so maybe you'll see nothing )

The background color is : #6c1f9c

**Comment by tranquvis** [comment]
![image](https://user-images.githubusercontent.com/8074528/38933360-0174deec-4319-11e8-9da1-41ddecb12b35.png)

**Comment by s-yous** [comment]
Wow 😍 It looks very nice on Google Play !
Thank you so much for giving me the opportunity and using my design as well.

I hope you like it <3

**Comment by s-yous** [comment]
Let me know if you need the logo or the icon in a specific size for the F-Droid or the Github page.

**Comment by tranquvis** [comment]
Design changes have already been made some time ago, so I close this issue.
