### ISSUE TITLE
Bug In "Simple SMS Remote" App(Button are not working after take tour)

### ISSUE THREAD

**Issue by rizwankhan003** [tranquvis/SimpleSmsRemote#26]
#### Expected behavior
I Expected that when i Click on simple sms remote app and click on any option like "setting" that i wanted to change it should be work.
#### Actual behavior
When I open the simple sms remote application and take a visit how he function in the wake of finishing visit steps again I tap on choice catch and click on setting catch that I needed to change a few settings yet the setting catch are not working then I tap on others discretionary catch they are likewise not working after take a tour.
#### How to reproduce
1. Download Simple Sms remote app from playstore
2. Install and Run it
3. Open the app clik on options button on top righ side
4. Now Click on Help tour button and take tour how he work
5. After completing tour Again Click on option button
6. Click on Setting Button
7. Note the bug
* Browser: HUAWEI Mate 10 lite
+ Version: 1.2.0
* Operating system: Android version 7.0

#### Recording Of The Bug
<iframe width="732" height="400" src="https://www.youtube.com/embed/5UMVnQLKWpI?ecver=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@rizwankhan/bug-in-simple-sms-remote-app-button-are-not-working-after-take-tour">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by onozasi** [comment]
Not just the settings function is affected by this, All the options (log, help tour and how-to-control) are also affected.
