### ISSUE TITLE
Bug on Simple Sms Remote: Clear whole log?  Has no "Ok" button to concur to request

### ISSUE THREAD

**Issue by gutzygwin** [tranquvis/SimpleSmsRemote#28]
#### Expected behavior
Simple Sms remote is an open source andriod application for controlling a mobile device through messaging. Clearing the log is performed by activating the log at the menu option on the top right hand side of the screen, then clearing the trash on log. 

#### Actual behavior
The case as it may be is a bit different when I try to perform this operation. Everything works fine from clicking on the log at the top of the screen to opening the log, clicking on the trash icon, right up on till the point a dialog shows **Clear whole log?** with no **OK** feature to concur with request of clearing the log. The box just displays **clear log?** with no additional information and hence the process can not easily be carried out successfully.

#### How to reproduce
* Click on the menu option at the top right corner of the application. 
* Click on log and this will appear. 
* Click on the trash icon as shown (see image below.  ![Screenshot_20180404-111455.png](https://cdn.utopian.io/posts/1466f7f8e674bbf0d4b990dc0ba99370716bScreenshot_20180404-111455.png)
* This dialog appears without an **OK** option to verify or concur to request in carrying out the operation. (see image below)  ![Screenshot_20180404-111538.png](https://cdn.utopian.io/posts/67a092f9bb865edc388e5e4243916e40db4aScreenshot_20180404-111538.png)

--------------------------------------------------------

* version of the application : **v 1.2.0**
* last updated : 12/7/17

--------------------------------------------------------

* Browser: F-driod / Simple Sms Remote
* Operating system: Andriod 7.0

#### Recording Of The Bug

https://youtu.be/gcL0-tH7wok
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gutzygwin/bug-on-simple-sms-remote-clear-log-has-no-ok-button-to-concur-to-request">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tranquvis** [comment]
Fixed with #24 .

**Comment by gutzygwin** [comment]
Thanks.

On Apr 13, 2018 18:09, "Andreas Kaltenleitner" <notifications@github.com>
wrote:

Fixed with #24 <https://github.com/tranquvis/SimpleSmsRemote/issues/24> .

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tranquvis/SimpleSmsRemote/issues/28#issuecomment-381201214>,
or mute the thread
