### ISSUE TITLE
Failed to send command execution reply to sender

### ISSUE THREAD

**Issue by xunil89** [tranquvis/SimpleSmsRemote#40]
Failed to send command execution reply to
sender
an unexpected error occurred
Los16
permission to send sms granted
![IMG_20200501_163015_409](https://user-images.githubusercontent.com/14961235/80817117-1b42a680-8bd1-11ea-946c-fd9d05d4c6ac.jpg)

**Comment by tranquvis** [comment]
I experienced the same issue on my phone with Android 9. I fixed it in the latest commit https://github.com/tranquvis/SimpleSmsRemote/commit/9aa14201c5d372d9c0e8d7828172b0d22d2aaf14.

**Comment by bbinet** [comment]
I'm also facing this same issue.
Is there a new release that includes this fix?

**Comment by tranquvis** [comment]
No. I will create a new release during week. I will then notify you again.
