### ISSUE TITLE
Publish command list?

### ISSUE THREAD

**Issue by Leviathanone** [tranquvis/SimpleSmsRemote#6]
It would be nice to have a place to find all of the commands that you can send, since you wouldn't have the phone if you're trying to remote control it and remembering all the commands might be difficult for some. maybe you can store this command list maybe on a github wiki in this repo

**Comment by tranquvis** [comment]
This might be true.
I have now added a [list](https://github.com/tranquvis/SimpleSmsRemote/wiki/Full-list-of-commands) to the repo's wiki.
