### ISSUE TITLE
Signal as default sms client

### ISSUE THREAD

**Issue by GitKalle** [tranquvis/SimpleSmsRemote#9]
I use [Signal](https://github.com/WhisperSystems/Signal-Android) as my default sms client. I try to send commands in encrypted and decrypted sms from an other phone with Signal. Both of them doesn't work.
Do you have experience to send commands over Signal?

**Comment by tranquvis** [comment]
I have tried sms without encryption and it worked. Encrypted messages don't seem to be broadcasted to other apps by Signal. Are you sure you sent the message via sms without encryption? (Long press on the send icon -> Sms)

**Comment by GitKalle** [comment]
I have done it in the same way. I'll do some more tests and give you a feedback.

**Comment by tranquvis** [comment]
Did you close the issue, because you couldn't reproduce it?
